version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: ./docker/dev-dockerfile
    volumes:
      - ./site:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
    environment:
      - JEKYLL_ENV=development
  build:
    command: jekyll build 
    image: jekyll/jekyll:latest
    volumes:
      - ./site:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000    
    environment:
      - ENV=production
  prod:
    build:
      context: .
      dockerfile: ./docker/prod-dockerfile
    ports:
      - 4000:80
